// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'FilmSimilar': string;
  'similarItem': string;
}
export const cssExports: CssExports;
export default cssExports;
