// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'FilmDetail': string;
  'Similar': string;
  'container': string;
  'wrapImg': string;
}
export const cssExports: CssExports;
export default cssExports;
